// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jbUUp9vjIFm_vgvtZxgDdcyGKB91QiY',
    appId: '1:801808014637:web:c76519c4e099ce359a87a4',
    messagingSenderId: '801808014637',
    projectId: 'desafio-care-lucas',
    authDomain: 'desafio-care-lucas.firebaseapp.com',
    storageBucket: 'desafio-care-lucas.appspot.com',
    measurementId: 'G-C68QGZEF98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPDuojcVEIZWWHD88NioVBLvAJyss-9s0',
    appId: '1:801808014637:android:6fc0e63bf72dd1b49a87a4',
    messagingSenderId: '801808014637',
    projectId: 'desafio-care-lucas',
    storageBucket: 'desafio-care-lucas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Pa8uPPqy2PNB-jhVJxALpaH8fEL2Kbk',
    appId: '1:801808014637:ios:ccf6bc7a665b3a9e9a87a4',
    messagingSenderId: '801808014637',
    projectId: 'desafio-care-lucas',
    storageBucket: 'desafio-care-lucas.appspot.com',
    iosClientId: '801808014637-a2ao9a9cscu0dt06701lls1oeqb3rot6.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Pa8uPPqy2PNB-jhVJxALpaH8fEL2Kbk',
    appId: '1:801808014637:ios:ccf6bc7a665b3a9e9a87a4',
    messagingSenderId: '801808014637',
    projectId: 'desafio-care-lucas',
    storageBucket: 'desafio-care-lucas.appspot.com',
    iosClientId: '801808014637-a2ao9a9cscu0dt06701lls1oeqb3rot6.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientListApp',
  );
}
